function dualLineGraphByBin(name, numBins, binSize, xVals, yLim, LLoc)
    figure('Name',name);
    
    subplot(2,1,1);
    linePerBinPerCond(numBins, binSize, xVals(:,1:3), yLim(1,:),...
        'MOT',...
        {'Single','MOTRes1st','VWMRes1st'}, LLoc{1});

    subplot(2,1,2);
    linePerBinPerCond(numBins, binSize, xVals(:,4:6), yLim(2,:),...
        'VWM',...
        {'Single','MOTRes1st','VWMRes1st'}, LLoc{2});
end